version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:5000
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root2
      MYSQL_PASSWORD: root2
      MYSQL_ROOT_PASSWORD: root2

    ports:
      - 33067:3306
    command: --bind-address=0.0.0.0 --skip-name-resolve
